packages:
  - "apps/*"
  - "contexts/*"
  - "libs/*"
  - "libs/*/*"

catalog:
  zod: "^4.6.5"

catalogs:
  nestjs12:
    "@nestjs/common": "12.0.4"
    "@nestjs/core": "12.0.4"
    "@nestjs/platform-express": "12.0.4"
    "@nestjs/microservices": "12.0.4"
    "@nestjs/cqrs": "12.0.0"
    "@nestjs/config": "12.0.0"
    "@nestjs/testing": "12.0.4"
    "@nestjs/jwt": "12.0.2"
    reflect-metadata: "^0.2.2"
    rxjs: "^7.8.2"
  tooling:
    typescript: "7.0.2"
    vitest: "^5.0.1"

allowBuilds:
  "@nestjs/core": true
  esbuild: true
  nx: true
