export {
  INTERVIEW_PAGES,
  KNOWLEDGE_PAGES,
  KNOWLEDGE_SEARCH_PARAMS,
  PLATFORM_OBJECT_PAGES,
  PLATFORM_PAGES,
  PLATFORM_SEARCH_PARAMS,
  PROJECT_PAGES,
  RETURN_TO_PARAM,
  ROUTE_PARAMS,
  ROUTES,
  WORKSPACE_PAGES,
  conversationPath,
  knowledgeItemPath,
  newKnowledgeItemPath,
  platformAgentPath,
  platformPath,
  platformSkillPath,
  projectPath,
  workspacePath,
  type PlatformPage,
  type ProjectPage,
  type WorkspacePage,
} from './routes';
