/** Names for the random workspace button, each with the alias it seeds. */
export const CELESTIAL_NAMES = [
  { alias: 'alpha-centauri', name: 'Alpha Centauri' },
  { alias: 'andromeda', name: 'Andromeda' },
  { alias: 'antares', name: 'Antares' },
  { alias: 'ariel', name: 'Ariel' },
  { alias: 'betelgeuse', name: 'Betelgeuse' },
  { alias: 'callisto', name: 'Callisto' },
  { alias: 'capella', name: 'Capella' },
  { alias: 'ceres', name: 'Ceres' },
  { alias: 'deimos', name: 'Deimos' },
  { alias: 'deneb', name: 'Deneb' },
  { alias: 'dione', name: 'Dione' },
  { alias: 'enceladus', name: 'Enceladus' },
  { alias: 'eris', name: 'Eris' },
  { alias: 'europa', name: 'Europa' },
  { alias: 'ganymede', name: 'Ganymede' },
  { alias: 'halley', name: 'Halley' },
  { alias: 'hyperion', name: 'Hyperion' },
  { alias: 'io', name: 'Io' },
  { alias: 'mars', name: 'Mars' },
  { alias: 'mercury', name: 'Mercury' },
  { alias: 'mimas', name: 'Mimas' },
  { alias: 'miranda', name: 'Miranda' },
  { alias: 'neptune', name: 'Neptune' },
  { alias: 'oberon', name: 'Oberon' },
  { alias: 'orion-nebula', name: 'Orion Nebula' },
  { alias: 'phobos', name: 'Phobos' },
  { alias: 'pluto', name: 'Pluto' },
  { alias: 'polaris', name: 'Polaris' },
  { alias: 'proxima-centauri', name: 'Proxima Centauri' },
  { alias: 'rhea', name: 'Rhea' },
  { alias: 'rigel', name: 'Rigel' },
  { alias: 'saturn', name: 'Saturn' },
  { alias: 'sirius', name: 'Sirius' },
  { alias: 'sombrero-galaxy', name: 'Sombrero Galaxy' },
  { alias: 'titan', name: 'Titan' },
  { alias: 'titania', name: 'Titania' },
  { alias: 'triton', name: 'Triton' },
  { alias: 'vega', name: 'Vega' },
  { alias: 'venus', name: 'Venus' },
  { alias: 'vesta', name: 'Vesta' },
  { alias: 'achernar', name: 'Achernar' },
  { alias: 'acrux', name: 'Acrux' },
  { alias: 'adhara', name: 'Adhara' },
  { alias: 'adrastea', name: 'Adrastea' },
  { alias: 'alcyone', name: 'Alcyone' },
  { alias: 'aldebaran', name: 'Aldebaran' },
  { alias: 'algol', name: 'Algol' },
  { alias: 'alhena', name: 'Alhena' },
  { alias: 'alnair', name: 'Alnair' },
  { alias: 'alnilam', name: 'Alnilam' },
  { alias: 'alnitak', name: 'Alnitak' },
  { alias: 'altair', name: 'Altair' },
  { alias: 'amalthea', name: 'Amalthea' },
  { alias: 'ananke', name: 'Ananke' },
  { alias: 'arcturus', name: 'Arcturus' },
  { alias: 'bellatrix', name: 'Bellatrix' },
  { alias: 'bianca', name: 'Bianca' },
  { alias: 'canopus', name: 'Canopus' },
  { alias: 'carme', name: 'Carme' },
  { alias: 'cartwheel-galaxy', name: 'Cartwheel Galaxy' },
  { alias: 'castor', name: 'Castor' },
  { alias: 'charon', name: 'Charon' },
  { alias: 'cordelia', name: 'Cordelia' },
  { alias: 'crab-nebula', name: 'Crab Nebula' },
  { alias: 'cygnus-x-1', name: 'Cygnus X-1' },
  { alias: 'despina', name: 'Despina' },
  { alias: 'elara', name: 'Elara' },
  { alias: 'electra', name: 'Electra' },
  { alias: 'fomalhaut', name: 'Fomalhaut' },
  { alias: 'haumea', name: 'Haumea' },
  { alias: 'helene', name: 'Helene' },
  { alias: 'iapetus', name: 'Iapetus' },
  { alias: 'janus', name: 'Janus' },
  { alias: 'juliet', name: 'Juliet' },
  { alias: 'larissa', name: 'Larissa' },
  { alias: 'leda', name: 'Leda' },
  { alias: 'makemake', name: 'Makemake' },
  { alias: 'merope', name: 'Merope' },
  { alias: 'metis', name: 'Metis' },
  { alias: 'mintaka', name: 'Mintaka' },
  { alias: 'naiad', name: 'Naiad' },
  { alias: 'nereid', name: 'Nereid' },
  { alias: 'ophelia', name: 'Ophelia' },
  { alias: 'pan', name: 'Pan' },
  { alias: 'pandora', name: 'Pandora' },
  { alias: 'pasiphae', name: 'Pasiphae' },
  { alias: 'phoebe', name: 'Phoebe' },
  { alias: 'pinwheel-galaxy', name: 'Pinwheel Galaxy' },
  { alias: 'pollux', name: 'Pollux' },
  { alias: 'portia', name: 'Portia' },
  { alias: 'proteus', name: 'Proteus' },
  { alias: 'puck', name: 'Puck' },
  { alias: 'regulus', name: 'Regulus' },
  { alias: 'rosalind', name: 'Rosalind' },
  { alias: 'spica', name: 'Spica' },
  { alias: 'sycorax', name: 'Sycorax' },
  { alias: 'telesto', name: 'Telesto' },
  { alias: 'thebe', name: 'Thebe' },
  { alias: 'umbriel', name: 'Umbriel' },
  { alias: 'whirlpool-galaxy', name: 'Whirlpool Galaxy' },
] as const;
